// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjbwacfqjwzzmolgsbrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqYndhY2Zxand6em1vbGdzYnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTcxNzksImV4cCI6MjA2Njg5MzE3OX0.03uEliAl54Yj3lmayFTgJgkiDd3fvfDwWap8qe_U3h0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});